version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:22
    working_dir: /usr/src/clean-node
    restart: always
    command: bash -c "npm install --only=prod && npm run debug -- --no-source-maps"
    volumes:
      - ./dist/:/usr/src/clean-node/dist/
      - ./package.json:/usr/src/clean-node/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
